#ifndef _CONSTANTES_H_
#define _CONSTANTES_H_

#define TOTALUSERS 138494
#define TOTALTAGS 1000
#define TOTALJOGADORES 18944
#define DIMENSAOGERAL 100
#define TOTALSOFIFAID 300000
#define TOTALPOSICOES 50
#define USERJOGADORESMAX 20
#define DIMENSAO_POSITION 5
#define TOTALCARACTERESASCII 256

#define TAMANHOPEQUENO 10
#define PEQUENOIMPRESSAO 8
#define TAMANHOAUX 20
#define TAMANHOGRANDE 45
#define TAMANHONUMERO 7

#define ARQUIVOPLAYER "players.csv"
#define ARQUIVORATING "rating.csv"
#define ARQUIVOTAGS "tags.csv"

#define MAXTAGS 15000
#define MINIMOAVALIACOES 1000

#define ESC 27
#define APOSTROFE 39

#endif