#ifndef _DEFINICOES_H_
#define _DEFINICOES_H_

#define TOTALUSERS 138494
#define TOTALTAGS 1000
#define TOTALJOGADORES 18944
#define DIMENSAO_GERAL 70
#define TOTALSOFIFAID 300000
#define TOTALPOSITIONS 50
#define USERJOGADORESMAX 20
#define DIMENSAO_POSITION 5

#define TAMANHOPEQUENO 10
#define PEQUENOIMPRESSAO 8
#define TAMANHOAUX 20
#define TAMANHOGRANDE 45
#define TAMANHONUMERO 6

#define ARQUIVOPLAYER "players.csv"
#define ARQUIVORATING "rating.csv"
#define ARQUIVOTAGS "tags.csv"

#define MAXTAGS 15000
#define MINIMOAVALIACOES 1000

#define ESC 27
#define APOSTROFE 39

#endif